services:
  - type: web
    name: bfef-kenya-frontend
    env: static
    buildCommand: npm install && npm run build:prod
    staticPublishPath: ./dist/bfef-kenya-frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
